### PR TITLE
Use parameters

### PR DESCRIPTION
**Pull request by Saphyel**
Use parameters from services.yml rather than config file.

Before of merge think about monolog.

### CODE REVIEW

**Comment by pvhee** [comment]
This change will need a documentation update as well @Saphyel

**Comment by Saphyel** [comment]
@pvhee updated

**Comment by pvhee** [comment]
@Saphyel don't think this is still relevant?

**Comment by Saphyel** [comment]
@pvhee I think maybe is better close it for now.

**Pull request closed without merging**
